### ISSUE TITLE
NoSuchMethodError on ContainerUtil.notNullize in PHPStorm 7.1.5

### ISSUE THREAD

**Issue by mikmanic** [hsz/idea-gitignore#232]
After updating to v1.4.1 (2016-05-24) I started getting NoSuchMethodError:

```
com.intellij.util.containers.ContainerUtil.notNullize(Ljava/util/List;)Ljava/util/List;: com.intellij.util.containers.ContainerUtil.notNullize(Ljava/util/List;)Ljava/util/List;
java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.notNullize(Ljava/util/List;)Ljava/util/List;
	at mobi.hsz.idea.gitignore.util.ExternalExec.getUnignoredFiles(ExternalExec.java:83)
	at mobi.hsz.idea.gitignore.daemon.AddUnversionedFilesNotificationProvider.createNotificationPanel(AddUnversionedFilesNotificationProvider.java:131)
	at mobi.hsz.idea.gitignore.daemon.AddUnversionedFilesNotificationProvider.createNotificationPanel(AddUnversionedFilesNotificationProvider.java:59)
	at com.intellij.ui.EditorNotifications$3$1.run(EditorNotifications.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.ui.EditorNotifications$3.run(EditorNotifications.java:80)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2000)
	at com.intellij.ui.EditorNotifications.updateNotifications(EditorNotifications.java:77)
	at com.intellij.ui.EditorNotifications$2.fileOpened(EditorNotifications.java:71)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:234)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:216)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
	at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
	at com.sun.proxy.$Proxy74.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$12.run(FileEditorManagerImpl.java:911)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13$1.run(FileEditorManagerImpl.java:960)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:638)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:622)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:592)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:59)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:488)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2000)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:466)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:461)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:64)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.a(ToolWindowManagerImpl.java:237)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$200(ToolWindowManagerImpl.java:86)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$2.run(ToolWindowManagerImpl.java:149)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:297)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
